### ISSUE TITLE
Non-free bits in release

### ISSUE THREAD

**Issue by dschwoerer** [diegojromerolopez/gelidum#24]
I am currently trying to [package gelidum for fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2008657), however I noticed that the package is non-free, as it contains a CC BY-NC 2.0 image.

This is listed [in fedora license list](https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses_3) as a non-acceptable license.
While I could remove the image always from the release, not being forced to do this would be greatly appreciated.

The NC part might also violate the [PYPI terms of use](https://pypi.org/policy/terms-of-use/) but I am not a lawyer ...

**Comment by dschwoerer** [comment]
Thanks, much appreciated :+1: 

I noticed one minor issue, version.txt and requirements.txt are installed to $PREFIX. I currently just delete them, but it would be cleaner if they wouldn't be installed in the first place.

**Comment by diegojromerolopez** [comment]
Removing version.txt and requirements.txt from data_files did that (why did I put it there in the first place? I wonder).

Version 0.5.6 (already in pypi) is updated with that change. Please, confirm if that works for you.

Thanks for the reporting!

**Comment by johnomotani** [comment]
Unfortunately removing `version.txt` and `requirements.txt` breaks the `conda-forge` setup - that apparently needs to run `setup.py` again and [errors because it can't find the files](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=404927&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=429).

I think the easiest fix for this would be to:
* remove `version.txt` and just put the version number directly in `setup.py` (as long as it's not needed anywhere else?)
    * there's also [`setuptools_scm`](https://pypi.org/project/setuptools-scm/) which can automatically create the version number from the git tags, but that's probably overkill here.
* put the dependencies (if/when there are any) in `setup.py` and change requirements.txt to be just:
    ```
    .
    ```
    which, if `requirements.txt` is ever used, effectively tells `pip` to get the requirements from `setup.py` (for more on why both `requirements.txt` and `setup.py` exist, and might be different, see e.g. https://caremad.io/posts/2013/07/setup-vs-requirement/).

**Comment by diegojromerolopez** [comment]
@johnomotani could you please check this PR https://github.com/diegojromerolopez/gelidum/pull/27?

**Comment by diegojromerolopez** [comment]
@johnomotani merged and updated to 0.5.7 in pypi. Thank you!
